package nl.wesselbarten.museumapp.domain.model

data class ExtendedArtObject(
    val objectNumber: String,
    val id: String,
    val links: Links,
    val title: String,
    val hasImage: Boolean,
    val principalOrFirstMaker: String?,
    val longTitle: String,
    val showImage: Boolean,
    val permitDownload: Boolean,
    val webImage: WebImage?,
    val headerImage: HeaderImage?,
    val productionPlaces: List<String>,
    val description: String?,
    val documentation: List<String>,
    val exhibitions: List<Any>,
    val labelText: Any?,
    val language: String,
    val location: String?,
    val makers: List<Any>,
    val materials: List<String>,
    val objectCollection: List<String>?,
    val objectTypes: List<String>,
    val physicalMedium: String,
    val physicalProperties: List<Any>,
    val plaqueDescriptionDutch: String?,
    val plaqueDescriptionEnglish: String?,
    val principalMaker: String,
    val principalMakers: List<PrincipalMaker>,
    val subTitle: String,
    val techniques: List<Any>,
    val titles: List<String>
)